# Generated by Django 5.1.4 on 2024-12-09 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklistitem_set', to='core.checklist'),
        ),
    ]
